
CREATE TABLE user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(75) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `lnm_btp`.`product` (
  `productId` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `category` ENUM("elect") NOT NULL,
  `price` INT(5) NOT NULL,
  `owner` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `available` TINYINT NOT NULL DEFAULT 1,
  `buyer` VARCHAR(45) NULL,
  `sell_time` DATETIME NULL,
  PRIMARY KEY (`productId`));